run-AND-raise
CZ-NIC/run-or-raise pull request #27
Opened 2021-02-18 12:16 UTC by darkermatter

Add ,& to the end of the shortcut definition to both raise the window and run the launch script.

For example, I use it to control which tmux session to switch to.

2021-02-18 13:01 UTC, e3rd requested changes
* Add a note to CHANGELOG and description and some examples to README.md
* In the future, I plan to add more commands so the syntax might change.
* I have in my mind syntax `shortcut:instruction,command,[wm_class],[title]` where `:instruction` is an optional part. So your use case would look like `<Super>t:always-run,tmux,Tmux_class`. What do you think about the syntax?

2021-02-18 17:46 UTC, darkermatter commented on extension.js
> +                if (runAndRaise) {
If you don't have runAndRaise enabled, this would never run the command, would it?

2021-02-18 17:51 UTC, darkermatter commented on extension.js
> +            runAndRaise = false;
I mainly program in Go therefore I usually prefer readability and explicitness over short-circuiting, implicitness and whatnot. That said, no problem, I'll make the change.

2021-02-18 17:53 UTC, darkermatter commented on extension.js
> +                if (runAndRaise) {
The new syntax looks like a good idea. It shouldn't break existing configs.

2021-02-18 17:55 UTC, darkermatter commented on extension.js
> +            var wm_class, wmFn, title, titleFn, runAndRaise;
did I mention I'm a Go programmer ;-)

2021-02-18 17:57 UTC, darkermatter commented on extension.js
> +            if (shortcut.length > 4 && shortcut[4] === "&") {
perhaps this would be better than the syntax you proposed earlier - again, it doesn't break existing configs.

2021-02-18 18:00 UTC, darkermatter commented on extension.js
> +            if (shortcut.length > 4 && shortcut[4] === "&") {
it wouldn't be so much as an 'instruction' but rather a 'mode'

2021-02-18 18:34 UTC, darkermatter commented
I'm withdrawing this PR for a more complete one.

2021-02-18 18:34 UTC, closed without merging

2021-02-19 15:04 UTC, e3rd commented on extension.js
> +            var wm_class, wmFn, title, titleFn, runAndRaise;
Tell me more, I don't get it :) What is specific fo Go programmers?

2021-02-19 15:04 UTC, e3rd commented on extension.js
> +            if (shortcut.length > 4 && shortcut[4] === "&") {
ok, `mode` is much better

2021-02-19 15:05 UTC, e3rd commented on extension.js
> +            var wm_class, wmFn, title, titleFn, runAndRaise;
Ah, I get it, ok

2021-02-19 15:06 UTC, e3rd commented on extension.js
> +                if (runAndRaise) {
my bad, there should have been `(!seen || runAndRaise)` I suppose